### ISSUE TITLE
Recent issue

### ISSUE THREAD

**Issue by Sparko75** [QiCuiHub/discord-audio-pipe#10]
The program automatically shut down after trying to launch.
My friend can't start the program too.
Here is the errors log

Error on main
Traceback (most recent call last):
  File "main.pyw", line 31, in <module>
  File "site-packages\discord\client.py", line 640, in run
  File "site-packages\discord\client.py", line 621, in runner
  File "site-packages\discord\client.py", line 585, in start
  File "site-packages\discord\client.py", line 499, in connect
  File "site-packages\discord\client.py", line 463, in _connect
  File "site-packages\discord\gateway.py", line 471, in poll_event
  File "site-packages\discord\gateway.py", line 425, in received_message
  File "site-packages\discord\state.py", line 750, in parse_guild_create
  File "site-packages\discord\state.py", line 725, in _get_create_guild
  File "site-packages\discord\guild.py", line 297, in _from_data
  File "site-packages\discord\guild.py", line 326, in _sync
  File "site-packages\discord\channel.py", line 553, in __init__
  File "site-packages\discord\channel.py", line 584, in _update
  File "site-packages\discord\abc.py", line 294, in _fill_overwrites
TypeError: __new__() got an unexpected keyword argument 'deny_new'

**Comment by QiCuiHub** [comment]
Looks like this is related to https://github.com/Rapptz/discord.py/issues/5109. If you are using the source code, updating to the latest version of discord.py[voice] should fix it, otherwise I'll update the release to fix the issue.

**Comment by Sparko75** [comment]
Thank you very much, I used source code and it works perfectly.
Oh, and I see that you released an update that's perfect ! Very good job :)

**Comment by QiCuiHub** [comment]
Thanks!
