### ISSUE TITLE
socket.gaierror: [Errno 11001] getaddrinfo failed

### ISSUE THREAD

**Issue by dtrenz** [QiCuiHub/discord-audio-pipe#27]
Everything worked fine a week ago, but all of a sudden the audio pipe doesn't seen to be able to connect to discord.

```
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "discord\client.py", line 558, in connect
  File "asyncio\tasks.py", line 442, in wait_for
  File "discord\gateway.py", line 305, in from_client
  File "discord\http.py", line 917, in get_gateway
  File "discord\http.py", line 185, in request
  File "aiohttp\client.py", line 1117, in __aenter__
  File "aiohttp\client.py", line 521, in _request
  File "aiohttp\connector.py", line 535, in connect
  File "aiohttp\connector.py", line 892, in _create_connection
  File "aiohttp\connector.py", line 1011, in _create_direct_connection
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discord.com:443 ssl:default [getaddrinfo failed]
2021-02-07 20:58:38 Error on main
Traceback (most recent call last):
  File "main.pyw", line 136, in main
  File "discord\client.py", line 661, in start
  File "discord\client.py", line 561, in connect
  File "discord\gateway.py", line 587, in poll_event
discord.errors.ConnectionClosed: Shard ID None WebSocket closed with 4004
```

**Comment by QiCuiHub** [comment]
From what I can see, socket 4004 = Authentication Failed. On thing you could try is to regenerate a new token for your bot, and make sure there aren't any newlines and spaces at the end of the token, (i'll have to strip those out in a future release).

**Comment by dtrenz** [comment]
I regenerated the token, and made sure there aren't any newlines or whitespaces after it in the token.txt file. Does it matter if I previously kicked the bot from a voice channel?

**Comment by QiCuiHub** [comment]
The bot is failing to log in at all, so I don't think kicking the bot from one voice channel is causing the issue. Are you using the .exe or the source code? I have run into `getaddrinfo failed` before with #11 source code only, and updating to the latest discord.py with pip solved that issue. 

But the strange thing is you've mentioned that it was working before. Try running:
`curl https://discord.com/api/v8/gateway/bot -H "Authorization: Bot <Token>"`
in a terminal and replace `<Token>` with your bot token. This will tell you if you've hit some rate limit.

If that doesn't work, the only other thing I can think of is that something changed with your firewall, and its blocking discord.com

**Comment by dtrenz** [comment]
This is what I got from `curl`:
```sh
{"url": "wss://gateway.discord.gg", "shards": 1, "session_start_limit": {"total": 1000, "remaining": 1000, "reset_after": 0, "max_concurrency": 1}}
```

**Comment by dtrenz** [comment]
I'm dumb. I had to add the bot to the server again via the OAuth URL. Derp. Got it working now, thank you for this awesome project!
