### ISSUE TITLE
Version for MacOS

### ISSUE THREAD

**Issue by r-valyar** [QiCuiHub/discord-audio-pipe#30]
This is amazing tool and I would like to ask if there will be version for macOS?

**Comment by QiCuiHub** [comment]
The program can work for mac and a binary can be compiled. Unfortunately I don't have a macOS device to test the steps to get it compiled. 

I know people have gotten it working using the source code and command line on mac, I think opus and portaudio are additional dependencies that mac needs to get working.

**Comment by r-valyar** [comment]
I have macOS on M1 device and I can try to achieve something if there is some guidance on the topic. Any resource I can look at?

**Comment by QiCuiHub** [comment]
I use Github Actions and PyInstaller to automatically build and upload an exe everytime I make a new release. Github actions supports macOS instances and when PyInstaller is run in a macOS environment it will make an executable for macOS. 

The steps will be similar but syntax and dependencies will probably change. You'll need to add a macOS workflow to the [workflow file](https://github.com/QiCuiHub/discord-audio-pipe/blob/master/.github/workflows/main.yml) and probably create a [spec file](https://github.com/QiCuiHub/discord-audio-pipe/blob/master/build/main.spec) thats specific for macOS.

Some resources you can look at
https://pyinstaller.readthedocs.io/en/stable/usage.html#building-mac-os-x-app-bundles
https://pyinstaller.readthedocs.io/en/stable/spec-files.html
https://docs.github.com/en/actions/learn-github-actions

**Comment by scooper4711** [comment]
I used brew to install the prerequisites, and the UI comes up nicely, or I am able to use the command line.
However, I never get the output "Playing audio in {channel.name}" from cli.py.
I inserted print statements prior to that and everything up to ```voice.play(discord.PCMAudio(stream))``` works.
I don't know the discord API or the voice API. Thoughts on my next steps?

Oh yeah - unsurprisingly, the bot doesn't play any audio.

**Comment by scooper4711** [comment]
Update: found the discord.log. The following error is in it:
```
2021-08-30 18:09:21,189:DEBUG:discord.gateway: Sending voice websocket frame: {'op': 5, 'd': {'speaking': 1, 'delay': 0}}.
2021-08-30 18:09:21,189:DEBUG:discord.gateway: Sending voice websocket frame: {'op': 5, 'd': {'speaking': 0, 'delay': 0}}.
2021-08-30 18:09:21,193:INFO:discord.opus: error has happened in opus_encoder_ctl
2021-08-30 18:09:21,193:INFO:discord.opus: "invalid argument" has happened
```

**Comment by scooper4711** [comment]
if this helps, I have version 1.3.1 of opus installed.

**Comment by scooper4711** [comment]
Reducing the samplerate from 48000 to 48 gets rid of the invalid argument error, but now no error is output and it still doesn't output audio.

**Comment by scooper4711** [comment]
Just found the DAP_error.log file. Here's what happens with the sample rate set to 48 (not surprising - including only to contrast with the next error)
```
  File "/opt/homebrew/lib/python3.9/site-packages/sounddevice.py", line 2738, in _check
    raise PortAudioError(errormsg, err)
sounddevice.PortAudioError: Error opening RawInputStream: Invalid sample rate [PaErrorCode -9997]
```
Here's the error with the default sample rate from git
```
2021-08-30 20:35:37 Error on cli connect
Traceback (most recent call last):
  File "/Users/stephen/git/discord-audio-pipe/cli.py", line 18, in connect
    voice.play(discord.PCMAudio(stream))
  File "/opt/homebrew/lib/python3.9/site-packages/discord/voice_client.py", line 564, in play
    self.encoder = opus.Encoder()
  File "/opt/homebrew/lib/python3.9/site-packages/discord/opus.py", line 294, in __init__
    self.set_fec(True)
  File "/opt/homebrew/lib/python3.9/site-packages/discord/opus.py", line 329, in set_fec
    _lib.opus_encoder_ctl(self._state, CTL_SET_FEC, 1 if enabled else 0)
  File "/opt/homebrew/lib/python3.9/site-packages/discord/opus.py", line 92, in _err_lt
    raise OpusError(result)
discord.opus.OpusError: invalid argument
2021-08-30 20:35:37 Task exception was never retrieved
future: <Task finished name='Task-2' coro=<connect() done, defined at /Users/stephen/git/discord-audio-pipe/cli.py:7> exception=SystemExit(1)>
Traceback (most recent call last):
  File "/Users/stephen/git/discord-audio-pipe/cli.py", line 18, in connect
    voice.play(discord.PCMAudio(stream))
  File "/opt/homebrew/lib/python3.9/site-packages/discord/voice_client.py", line 564, in play
    self.encoder = opus.Encoder()
  File "/opt/homebrew/lib/python3.9/site-packages/discord/opus.py", line 294, in __init__
    self.set_fec(True)
  File "/opt/homebrew/lib/python3.9/site-packages/discord/opus.py", line 329, in set_fec
    _lib.opus_encoder_ctl(self._state, CTL_SET_FEC, 1 if enabled else 0)
  File "/opt/homebrew/lib/python3.9/site-packages/discord/opus.py", line 92, in _err_lt
    raise OpusError(result)
discord.opus.OpusError: invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/stephen/git/discord-audio-pipe/main.pyw", line 166, in <module>
    loop.run_until_complete(main(bot))
  File "/opt/homebrew/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "/opt/homebrew/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
  File "/opt/homebrew/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 1890, in _run_once
    handle._run()
  File "/opt/homebrew/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/stephen/git/discord-audio-pipe/cli.py", line 24, in connect
    sys.exit(1)
SystemExit: 1
```

**Comment by scooper4711** [comment]
Running on an Intel Mac, I don't get that error, I instead get this error:
```
||PaMacCore (AUHAL)|| Error on line 1277: err='-66748', msg=Unknown Error
Exception in voice thread Thread-3
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/discord/player.py", line 603, in run
    self._do_run()
  File "/usr/local/lib/python3.9/site-packages/discord/player.py", line 590, in _do_run
    data = self.source.read()
  File "/usr/local/lib/python3.9/site-packages/discord/player.py", line 117, in read
    ret = self.stream.read(OpusEncoder.FRAME_SIZE)
  File "/Users/stephen/git/discord-audio-pipe/sound.py", line 18, in read
    data = self.stream.read(frames, exception_on_overflow = False)[0]
AttributeError: 'NoneType' object has no attribute 'read'
```

**Comment by scooper4711** [comment]
```
2021-09-02 22:01:03 Error on change_device
Traceback (most recent call last):
  File "/Users/stephen/git/discord-audio-pipe/gui.py", line 142, in change_device
    self.stream.change_device(selection)
  File "/Users/stephen/git/discord-audio-pipe/sound.py", line 28, in change_device
    self.stream = sd.RawInputStream(device=num)
  File "/usr/local/lib/python3.9/site-packages/sounddevice.py", line 1186, in __init__
    _StreamBase.__init__(self, kind='input', wrap_callback='buffer',
  File "/usr/local/lib/python3.9/site-packages/sounddevice.py", line 892, in __init__
    _check(_lib.Pa_OpenStream(self._ptr, iparameters, oparameters,
  File "/usr/local/lib/python3.9/site-packages/sounddevice.py", line 2738, in _check
    raise PortAudioError(errormsg, err)
sounddevice.PortAudioError: Error opening RawInputStream: Internal PortAudio error [PaErrorCode -9986]
2021-09-02 22:01:06 Task was destroyed but it is pending!
task: <Task pending name='Task-3' coro=<GUI.run_Qt() running at /Users/stephen/git/discord-audio-pipe/gui.py:381> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x113c9dd60>()]>>
```

**Comment by QiCuiHub** [comment]
Thanks for taking a look, apparently the command for installing PortAudio is
```
brew install portaudio --HEAD
```
Without the --head part, other people are reporting errors

**Comment by scooper4711** [comment]
Awesome! I got that to work on my Intel Mac. However, on my M1 Mac, I still get the Illegal Argument exception from the sample rate. 
Not sure what sample rate I should use.

**Comment by QiCuiHub** [comment]
From your error logs, it looks like the function `opus_encoder_ctl(...)` from the M1 opus library is expecting different arguments. You could try downgrading your opus or try `brew install opus --HEAD` like for PortAudio, although I'm not sure if that will fix the issue.

**Comment by r-valyar** [comment]
Any luck with the macOS for M1 port?

**Comment by oo7goofy** [comment]
Bump. This would be excellent if someone could get this working on MacOS.

**Comment by xuo-lynn** [comment]
bump having same issues

**Comment by QiCuiHub** [comment]
The issue should be fixed now in discord.py, you will have to get a dev version of d.py instead of the one in the requirements.txt
```
$ git clone https://github.com/Rapptz/discord.py
$ cd discord.py
$ python3 -m pip install -U .[voice]
```

**Comment by QiCuiHub** [comment]
discord.py 2.0.0 released and contains the fix for this issue https://github.com/Rapptz/discord.py/issues/8046, updated the requirements
