### ISSUE TITLE
(APPLICATION BROKEN) Exception occurred during Voice Protocol voice server update handler

### ISSUE THREAD

**Issue by HappyJuiceLive** [QiCuiHub/discord-audio-pipe#38]
Been using this bot for a few months now, just this morning found it unable to connect to any VC's. 
I tried resetting the bot token, reinviting it, etc. no luck.

**To Reproduce**
Simply attempt to connect to a VC

**Expected behavior**
A connection cannot be established when connecting to a VC
![Screenshot_1](https://user-images.githubusercontent.com/93631817/222236237-a7bffe2b-f6c1-4eef-98f2-6a968af3a667.png)

**Error log**
```
2023-03-01 10:39:06 Exception occurred during Voice Protocol voice server update handler
Traceback (most recent call last):
  File "discord\state.py", line 102, in logging_coroutine
  File "discord\voice_client.py", line 295, in on_voice_server_update
AttributeError: 'NoneType' object has no attribute 'close'
```

**System Info**
 - Windows 11
 - Executable
 - dap-2.2-win64.exe

**Comment by QiCuiHub** [comment]
Discord recently made a change to their API that breaks older versions of discord.py, I'll need to fix the GitHub actions and rebuild the binary. The only way to get it working for now is to use the source code and install the dev version of discord.py.

**Comment by QiCuiHub** [comment]
Created new release [dap-2.3-win64.exe](https://github.com/QiCuiHub/discord-audio-pipe/releases/download/2.3/dap-2.3-win64.exe)
