### ISSUE TITLE
SSL Verification failed

### ISSUE THREAD

**Issue by matiasba** [QiCuiHub/discord-audio-pipe#9]
I'm getting the following error when trying to launch the latest release on windows.

Error on main
Traceback (most recent call last):
  File "site-packages\aiohttp\connector.py", line 936, in _wrap_create_connection
  File "asyncio\base_events.py", line 985, in create_connection
  File "asyncio\base_events.py", line 1013, in _create_connection_transport
  File "asyncio\sslproto.py", line 530, in data_received
  File "asyncio\sslproto.py", line 189, in feed_ssldata
  File "ssl.py", line 774, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1076)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.pyw", line 31, in <module>
  File "site-packages\discord\client.py", line 640, in run
  File "site-packages\discord\client.py", line 621, in runner
  File "site-packages\discord\client.py", line 584, in start
  File "site-packages\discord\client.py", line 442, in login
  File "site-packages\discord\http.py", line 261, in static_login
  File "site-packages\discord\http.py", line 165, in request
  File "site-packages\aiohttp\client.py", line 1012, in __aenter__
  File "site-packages\aiohttp\client.py", line 483, in _request
  File "site-packages\aiohttp\connector.py", line 523, in connect
  File "site-packages\aiohttp\connector.py", line 859, in _create_connection
  File "site-packages\aiohttp\connector.py", line 1004, in _create_direct_connection
  File "site-packages\aiohttp\connector.py", line 986, in _create_direct_connection
  File "site-packages\aiohttp\connector.py", line 939, in _wrap_create_connection
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host discordapp.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1076)')]

I check discordapp.com and the certificate is not expired

**Comment by QiCuiHub** [comment]
It seems like there is an issue with the certificates in your python installation or computer

I'm not sure what might be causing it but here are some suggestions that may fix your issue
- Visit the Discord site with IE to acquire the SSL certificate
- running ``certutil -generateSSTFromWU roots.sst && certutil -addstore -f root roots.sst && del roots.sst`` in administrator powershell

If you want the nuclear but insecure option in ``main.pyw`` you can ``import aiohttp`` and replace line 26 with ``bot = discord.Client(loop=loop, connector=aiohttp.TCPConnector(verify_ssl=False))`` to disable ssl checks

**Comment by QiCuiHub** [comment]
Update: it seems like this is a widespread issue because a root certificate expired in the windows chain. https://github.com/Rapptz/discord.py/issues/4159

**Comment by IAmNotRyan** [comment]
Windows:

Go to start, type internet explorer. Run as admin.
Go do https://discord.com click on the padlock icon.
Click view certificates
Click install certificates, choose either user or local machine.
Click Place all certificates in the following store
Choose Trusted Root Certification Authorities
Enjoy.

**Comment by decendium** [comment]
> Click install certificates,

i dont see this 
![image](https://user-images.githubusercontent.com/54756899/85662826-5f5c9f80-b686-11ea-9ca6-c0739db24ab9.png)

**Comment by QiCuiHub** [comment]
This seems to be the accepted solution for manually installing the cert in the discord.py issue thread:

> The method that has had success in the [help channels](https://discord.gg/dpy) is the following:
> 
> Download the required certificate manually: https://crt.sh/?id=2835394
> The above link is provided by Sectigo.
> [This](https://beans-took-my-kids.reeee.ee/38qB2n.png) is where the actual download button is.
> 
> Once it has downloaded, double click it to install it. I believe installing it to the local computer and not the running user is the correct way to proceed, correct me if I am wrong there.

If installing it as local computer doesn't work, some users have had success installing it as current user.
